events {
    worker_connections 1024;  # Количество соединений на один процесс (увеличьте при высокой нагрузке)
    multi_accept on;          # Позволяет Nginx принимать несколько соединений сразу
    use epoll;                # Использование epoll для лучшей производительности (Linux)
}

http {
    include mime.types;  // Подключаем файл с типами MIME для правильного определения типа контента.

    sendfile on;  // Включаем использование sendfile для более быстрого и эффективного обслуживания файлов.

    tcp_nopush on;  // Включаем эту настройку для отправки данных блоками, улучшая производительность TCP-соединений.

    tcp_nodelay on;  // Включаем настройку для уменьшения задержек в передаче данных, чтобы ускорить отклик.

    keepalive_timeout 65;  // Настроим время ожидания для постоянных соединений (keep-alive), после чего соединение будет закрыто.

    types_hash_max_size 2048;  // Увеличиваем максимальный размер хеша для типов MIME (увеличивает количество поддерживаемых типов).

    server {
        listen 80;  // Слушаем порт 80 для HTTP трафика.
        listen [::]:80;  // Слушаем порт 80 для IPv6 трафика.
        server_name localhost;  // Указываем имя сервера. (доменное имя сайта).

        # Перенаправление HTTP → HTTPS
        return 301 https://$host$request_uri;  // Выполняем редирект с HTTP на HTTPS, сохраняя хост и URI.

    }

    server {
        listen 80 ssl http2;  // Слушаем порт 80 для HTTPS трафика с поддержкой HTTP/2.
        listen [::]:80 ssl http2;  // Слушаем порт 80 для IPv6 трафика с поддержкой HTTPS и HTTP/2.
        server_name localhost;  // Указываем имя сервера для HTTPS (доменное имя сайта).

        root /app;  // Указываем корневую директорию для сервера, где будут находиться файлы сайта.
        index index.html;  // Указываем файл по умолчанию, который будет использоваться, если запросить каталог.

        ssl_certificate /etc/nginx/ssl/cert.pem;  // Путь к SSL сертификату.
        ssl_certificate_key /etc/nginx/ssl/key.pem;  // Путь к закрытому ключу для SSL сертификата.

        # Безопасные SSL параметры
        ssl_protocols TLSv1.2 TLSv1.3;  // Устанавливаем поддержку только безопасных протоколов TLS.
        ssl_ciphers HIGH:!aNULL:!MD5;  // Устанавливаем шифры для SSL, отключаем слабые шифры.
        ssl_prefer_server_ciphers on;  // Принудительно используем шифры сервера вместо предпочтений клиента.

        # HTTP Security Headers
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;  // Включаем HSTS для защиты от атак с понижением безопасности.
        add_header X-Frame-Options DENY;  // Защищаем от атак через встроенные фреймы.
        add_header X-Content-Type-Options nosniff;  // Защищаем от атак на основе недокументированного типа контента.
        add_header Referrer-Policy no-referrer-when-downgrade;  // Устанавливаем политику реферера (не передавать реферер при переходах с HTTPS на HTTP).

        # CSP (Content Security Policy)
        location / {  // Настройка для корневого URL.
            try_files $uri /index.html;  // Если запрашиваемый файл не существует, отдаем index.html.
        }

        error_page 404 /src/pages/non-found/index.tsx;  // Страница ошибки 404 будет отображать /src/pages/non-found/index.tsx при отсутствии запрашиваемого ресурса.
    }
}

